const AccountActionTypes = {
  TOGGLE_ACCOUNT_SELECTOR: "TOGGLE_ACCOUNT_SELECTOR",
  SELECT_ACCOUNT: "SELECT_ACCOUNT",
  LOAD_ACCOUNT_START: "LOAD_ACCOUNT_START",
  LOAD_ACCOUNT_SUCCESS: "LOAD_ACCOUNT_SUCCESS",
  LOAD_ACCOUNT_FAIL: "LOAD_ACCOUNT_FAIL",
};

export default AccountActionTypes;
